config/routes.rb
Rails.application.routes.draw do
  root           'pages#home'
  get 'signup' => 'users#new'
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
  get 'what_is_lunch_meet' => 'pages#what_is_lunch_meet'
  get 'coldcuts'  => 'users#online'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

 resources :users do
 resources :conversations, :controller => "user_conversations"
 member do
 post :signin
 end
 collection do
 post :signout
 end
 end

 resources :conversations, :controller => "user_conversations" do
 resources :messages
 member do
 post :mark_as_read
 post :mark_as_unread
 end
 end
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
 has_many :user_conversations
 has_many :users, :through => :user_conversations
 has_many :messages

 accepts_nested_attributes_for :messages
end

app/models/message.rb
class Message < ActiveRecord::Base
 belongs_to :user
 belongs_to :conversation
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :user_conversations
    has_many :conversations, :through => :user_conversations
    has_many :messages, :through => :conversations
    attr_accessor :remember_token
    before_save {email.downcase!}
    validates :username, presence: true, length: {maximum: 20}
    validates :email, presence: true, length: {maximum: 109},
              format: {with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i},
              uniqueness: {case_sensitive: false}
    has_secure_password
    validates :password, length: { minimum: 6 }, allow_blank: true

    # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/models/user_conversation.rb
 class UserConversation < ActiveRecord::Base
 belongs_to :user
 belongs_to :conversation
 has_many :messages, :through => :conversation

 accepts_nested_attributes_for :conversation

 delegate :subject, :to => :conversation
 delegate :users, :to => :conversation

 attr_accessor :to
 before_create :create_user_conversations

private

 def create_user_conversations
 return if to.blank?

 to.each do |recip|
 UserConversation.create :user_id => recip, :conversation => conversation
 end
 end
 end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home ; end
    
    def about ; end
        
    def contact ; end
        
    def what_is_lunch_meet ; end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
        log_in user
        params[:session][:remember_me] == '1' ? remember(user) : forget(user)
        redirect_to user
      else
      # Create an error message.
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
      end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/user_conversations_controller.rb
class UserConversationsController < ApplicationController
    include ApplicationHelper

 def index
 @user = User.find params[:user_id]
 @conversations = @user.user_conversations
 end

 def show
 @conversation = UserConversation.find params[:id]
 end

 def new
 redirect_to users_path unless current_user

 @user = User.find params[:user_id]
 @conversation = @user.user_conversations.build
 @conversation.build_conversation.messages.build
 end

 def create
 redirect_to users_path unless current_user

 @conversation = UserConversation.new params[:user_conversation]
 @conversation.user = current_user
 @conversation.conversation.messages.first.user = current_user
 @conversation.save!
 redirect_to user_conversation_path(current_user, @conversation)
 end

 def mark_as_read
 @conversation = UserConversation.find params[:id]
 @conversation.update_attributes :read => true
 redirect_to user_conversation_path(current_user, @conversation)
 end

 def mark_as_unread
 @conversation = UserConversation.find params[:id]
 @conversation.update_attributes :read => false
 redirect_to user_conversation_path(current_user, @conversation)
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to LunchMeet!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def online
    @users = User.all
  end
  
  private
  
  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "LunchMeet!"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end
    
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
    
    # Returns the current logged-in user (if any).
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
  
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
  
  
end

app/helpers/user_conversations_helper.rb
module UserConversationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
    # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
      image_tag(gravatar_url, alt: user.username, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    LunchMeet 2015
  </small>
  <nav>
    
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <% if current_user %>
 <li>You are currently <%= current_user.username %>.</li>
 <% else %>
 <li>You are not currently signed in</li>
 <% end %>
      </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<head>
<div class="row clearfix">
		<div class="col-md-12 column">
			<ul class="nav nav-pills">
				<li class="active">
					<%= link_to "Home", root_path %>
				</li>
				<li>
					<%= link_to "What is LunchMeet?", what_is_lunch_meet_path %>
				</li>
		  <% if logged_in? %>
          <li><%= link_to "Users", coldcuts_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", "#" %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
            <% else %>
          <li><%= link_to "Log in", login_path %></li>
            <% end %>
			</ul>
	</div>
</div>
</head>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<%= favicon_link_tag "favicon.ico" %>
<head>
  <title><%= full_title(yield(:title)) %> </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
	  <%= render 'layouts/header' %>
	  <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
  </body>
</html>
  

app/views/pages/about.html.erb
<% provide(:title, "About") %>
<h1>About Us</h1>

<h2><p>LunchMeet was created by Adam Vilmin, Mylene Haus, and Kodi Collins for HackIllinois 2015. An employee of the restaurant industry since 2010, Adam came up with the idea for LunchMeet prior to the hackathon.</p> 

<p>This site was created using Bootstrap, Rails, Ruby, HTML, CSS, coffee, Red Bull, and free food.</p>

<p>Special thanks to Michael Hartl of <a href="https://www.railstutorial.org/">The Ruby on Rails Tutorial.</a> Without his wisdom, none of this would have been possible.</p>

<p>Silly logo and favicon designed by Mylene Haus.</p></h2>

<h3><p>Hire us!</p>
<p><a href="https://drive.google.com/file/d/0B1h8OsgUC9LZMkZJVlZhUmEwT3M/view?usp=sharing">Adam Vilmin</a> | <a href="https://drive.google.com/file/d/0B1h8OsgUC9LZRzdXVElldEplUm8/view?usp=sharing">Mylene Haus</a>
</p></h3>

app/views/pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact Us</h1>

<h2>
<p>
    Got something to say? Email us, or join us for a meal or two!
</p>    
<p><%= link_to "Adam Vilmin", "users/2" %> - crappyoats@gmail.com</p>
<p><%= link_to "Mylene Haus", "users/1" %> - mylene.haus@gmail.com</p>

    
</h2>

app/views/pages/home.html.erb
<!DOCTYPE HTML>

<div class="row clearfix">
		<div class="col-md-8 column">
			<%= image_tag("lunch_meet_logo.png", height: "600", width: "700") %>
		</div>
		<div class="col-md-4 column" class="row-md-10 row">
			<div class="jumbotron well">
				<font size="10px"><p align="center">
				 Welcome to <font color="teal">LunchMeet!</font>
				</font></p>
				<h2><p>
					<font color="teal">LunchMeet</font> is for finding new friends that love lunch as much as you do!
				</p></h2>
				<p align="center">
					<%= link_to "Sign up now!", signup_path , class: "btn btn-lg btn-primary" %>
				</p>
			</div>
		</div>
	</div>
</html>

app/views/pages/what_is_lunch_meet.html.erb
<% provide(:title, "What is LunchMeet?") %>
<h1>What is LunchMeet?</h1>
<h2><p>LunchMeet is a website where users can connect with others in their area and make new friends by meeting up for lunch, dinner, breakfast, drinks, or even just a snack. Bond over shared interests, mutual favorite foods, or even nothing in particular. Sign up today and see who you can meet!</p>
    
    
    
<p>Looking for info about us or LunchMeet's creation? <%= link_to "Click here! :)", about_path %></p>    
</h2>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/user_conversations/index.html.erb
<h1><%= @user.username %>'s Conversations</h1>

<ul>
 <% for conversation in @conversations do %>
 <li class="<%= conversation.read? ? 'read' : 'unread' %>"><%= link_to conversation.subject, user_conversation_path(conversation.user, conversation) %></li>
 <% end %>
</ul>

<%= link_to "Create a New Conversation", new_user_conversation_path(@user) %>

app/views/user_conversations/new.html.erb
<h1>New Conversation</h1>

<%= form_for(@conversation) do |f| %>
 <div>
 <%= f.label :to %>
 <% for user in User.all do %>
 <% next if user == current_user %>
 <%= check_box_tag "user_conversation[to][]", user.id %> <%= user.username %><br />
 <% end %>
 </div>
 <%= f.fields_for :conversation do |c| %>
 <div>
 <%= c.label :subject %>
 <%= c.text_field :subject %>
 </div>
 <%= c.fields_for :messages do |m| %>
 <div>
 <%= m.label :body %>
 <%= m.text_area :body %>
 </div>
 <% end %>
 <% end %>

 <%= f.submit %>
<% end %>

app/views/user_conversations/show.html.erb
<h1><%= @conversation.subject %></h1>

<div>
 <h2>People in this conversation:</h2>
 <ul>
 <% for user in @conversation.users do %>
 <li><%= link_to user.username, user %></li>
 <% end %>
 </ul>
</div>

<% for message in @conversation.messages do %>
 <div class="message"><%= time_ago_in_words(message.created_at) %> ago, <%= message.user.name %> wrote:
 <div class="message_body"><%= message.body %></div>
 </div>
<% end %>

<% if current_user == @conversation.username && !@conversation.read? %>
 <%= link_to "Mark as read", mark_as_read_conversation_path(@conversation), :method => :post %>
<% elsif current_user == @conversation.username && @conversation.read? %>
 <%= link_to "Mark as unread", mark_as_unread_conversation_path(@conversation), :method => :post %>
<% end %>
<br />

<%= link_to "Back to conversations", user_conversations_path(@user) %>

app/views/users/_form.html.erb
<%= form_for user do |f| %>
 <%= f.label :username %>
 <%= f.text_field :username %>
 <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit #{@user.username}") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target=_blank>change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<ul>
 <% for username in @users do %>
 <li><%= link_to user.username, user %></li>
 <% end %>
</ul>

app/views/users/new.html.erb
<% provide(:title, 'Sign up!') %>
<div class="center jumbotron">
    <h1>Sign up for LunchMeet</h1>
  <div class="row">
   <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control' %>
      
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
  </div>
</div>

app/views/users/online.html.erb
<%= provide(title: "Cold Cuts!") %>
<ul>
<% @users.each do |user| %>
  <div class="container">
      <font size="10px"><p align="center">
      <%= link_to  user.username , "users/#{user.id}" %>
      </font></p>
  </div>
  
<% end %>
</ul>

app/views/users/show.html.erb
<% provide(:title, @user.username) %>

<h1>
  <%= gravatar_for @user %>
  <%= @user.username %>
</h1>
<%= link_to "User's Conversations", user_conversations_path(@user) %>
<%= link_to "Create a New Conversation", new_user_conversation_path(@user) %>